# Generated by Django 3.1.7 on 2021-03-23 06:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aadhar',
            fields=[
                ('Aadhar_Number', models.BigIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(999999999999)])),
                ('Image', models.ImageField(default='', upload_to='dms/images')),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Sex', models.CharField(max_length=6)),
                ('DOB', models.DateField()),
                ('Mobile_NUmber', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('Enrollment_Number', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('QR_code', models.ImageField(default='', upload_to='dms/images')),
                ('Bar_Code', models.CharField(max_length=100)),
                ('Street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('fp_Actualdata', models.ImageField(default='', upload_to='dms/images')),
            ],
        ),
        migrations.CreateModel(
            name='aadharQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('MidName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField()),
                ('ename', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='dms/temp')),
                ('AadharNo', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(999999999999)])),
            ],
        ),
        migrations.CreateModel(
            name='licenceQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('MidName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pancardQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('MidName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RationQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('MidName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('HOF_name', models.CharField(max_length=100)),
                ('HOF_relation', models.CharField(max_length=50)),
                ('Father_or_Husband', models.BooleanField(default=False)),
                ('name_F_or_H', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aadhar_Number', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(999999999999)])),
                ('fp_User', models.ImageField(default='', upload_to='dms/images')),
            ],
        ),
        migrations.CreateModel(
            name='userlogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AadharNo', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(999999999999)])),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='voteridQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('MidName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VoterId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bar_Code', models.CharField(max_length=13)),
                ('Pic', models.ImageField(default='', upload_to='dms/images')),
                ('name', models.CharField(max_length=100)),
                ('FathersName', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('Sex', models.CharField(max_length=6)),
                ('Street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('pinCode', models.IntegerField()),
                ('AadharNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.aadhar', validators=[django.core.validators.MaxValueValidator(999999999999)])),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AppId', models.IntegerField()),
                ('message_senders_id', models.IntegerField()),
                ('message_senders_name', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=200)),
                ('System_message', models.CharField(max_length=200)),
                ('Aadhar_Number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.aadhar', validators=[django.core.validators.MaxValueValidator(999999999999)])),
            ],
        ),
        migrations.CreateModel(
            name='Ration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QR_code', models.ImageField(default='', upload_to='dms/images')),
                ('name', models.CharField(max_length=100)),
                ('HOF_name', models.CharField(max_length=100)),
                ('HOF_relation', models.CharField(max_length=50)),
                ('Father_or_Husband', models.BooleanField(default=False)),
                ('name_F_or_H', models.CharField(max_length=100)),
                ('dealersName', models.ImageField(default='', upload_to='dms/images')),
                ('Street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('pinCode', models.IntegerField()),
                ('AadharNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.aadhar', validators=[django.core.validators.MaxValueValidator(999999999999)])),
            ],
        ),
        migrations.CreateModel(
            name='PanCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QR_code', models.ImageField(default='', upload_to='dms/images')),
                ('name', models.CharField(max_length=100)),
                ('PRNnumber', models.CharField(max_length=15)),
                ('DOB', models.DateField()),
                ('signature', models.ImageField(default='', upload_to='dms/images')),
                ('pic', models.ImageField(default='', upload_to='dms/images')),
                ('AadharNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.aadhar', validators=[django.core.validators.MaxValueValidator(999999999999)])),
            ],
        ),
        migrations.CreateModel(
            name='DrivingLicence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LicenceNo', models.CharField(max_length=15)),
                ('Pic', models.ImageField(default='', upload_to='dms/images')),
                ('DateOfFirstIssue', models.DateField()),
                ('DOB', models.DateField()),
                ('contactInfo', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('validity', models.IntegerField()),
                ('Name', models.CharField(max_length=100)),
                ('Personal', models.BooleanField(default=True)),
                ('Commercial', models.BooleanField(default=False)),
                ('Street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('pinCode', models.IntegerField()),
                ('AadharNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.aadhar', validators=[django.core.validators.MaxValueValidator(999999999999)])),
            ],
        ),
    ]
