# Generated by Django 3.1.6 on 2021-04-20 07:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0002_auto_20210420_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='aadhar_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Actual_AadharNo', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(999999999999)])),
                ('AadharNo', models.CharField(max_length=10)),
                ('FirstName', models.CharField(max_length=10)),
                ('MidName', models.CharField(max_length=10)),
                ('LastName', models.CharField(max_length=10)),
                ('Street', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('pincode', models.CharField(max_length=10)),
                ('address_proof', models.CharField(max_length=10)),
                ('Sex', models.CharField(max_length=10)),
                ('Mobile_Number', models.CharField(max_length=10)),
                ('DOB', models.CharField(max_length=10)),
                ('birth_proof', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='aadhar_queries_status',
        ),
        migrations.RenameField(
            model_name='aadharq',
            old_name='Mobile_NUmber',
            new_name='Mobile_Number',
        ),
    ]
